quarkus.http.host=0.0.0.0
quarkus.http.port=${USER_SERVICE_PORT:8080}
quarkus.swagger-ui.always-include=true

# Cap.6 - Security (OIDC/Keycloak via Dev Services). Web app: Authorization Code Flow.
quarkus.oidc.application-type=web_app
quarkus.oidc.logout.path=/logout
quarkus.http.auth.permission.all-resources.paths=/*
quarkus.http.auth.permission.all-resources.policy=authenticated