quarkus.http.host=0.0.0.0
quarkus.http.port=${RESERVATION_PORT:8081}
quarkus.http.root-path=/reservation
quarkus.swagger-ui.always-include=true

quarkus.rest-client."org.acme.reservation.client.rental.RentalClient".uri=${RENTAL_SERVICE_URL:http://localhost:8082}
%docker.quarkus.rest-client."org.acme.reservation.client.rental.RentalClient".uri=http://rental-service:8082
quarkus.smallrye-graphql-client.inventory.url=${INVENTORY_SERVICE_URL:http://localhost:8083}/inventory/graphql